# Generated by Django 4.0.4 on 2022-11-16 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='langOrFrameworkUsed',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='githubLink',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='liveDemoLink',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolioImage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='portfolio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(upload_to='testimonials'),
        ),
    ]
